#!/bin/bash
set -e

folder_path="$1"
if [ ! -d "$folder_path" ]; then
    echo "PLease enter a valid folder name."
    exit 1
fi

current_datetime=$(date "+%H%M%S-%Y%m%d")
folder_name="$(basename "$folder_path")"
output_filename="$folder_name-$current_datetime.zip"

clear
echo "Size: $(du -sh "$folder_path")"

zip -r "$output_filename" "$folder_path"/*
find "$folder_path" -not -name "$folder_name" -not -name 'list.txt' -not -name '.' -exec rm -rf {} +

clear

echo "Zip completed at $(date "+%H:%M:%S")"
echo "File Size: $(du -sh "$output_filename")"
