#!/bin/bash

set -e

# Default values
output="$(date "+%Y%m%d-%H%M%S")"

# Function to display help
show_help() {
    echo "Usage: $(basename "$0") [-o, --output <path>] <file1> <file2> ..."
    exit 0
}

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -o | --output) output="$2"; shift 2;;
        -h | --help) show_help;;
        *) shift 1;;
    esac
done

zip -r "$output" "$@"

rm -rf "$@"