#!/bin/bash


if [[ "$#" -eq 0 ]]; then
  echo "Usage: $(basename "$0") <file> <folder>"
  exit 1
fi

s3-upload --domain "$S3_DOMAIN" --bucket-name "$S3_BUCKET_NAME" --bucket-path "$S3_BUCKET_PATH" --clean "$@"