#!/bin/bash

alias ll="ls -la"
alias c="clear"
alias ..='cd ..'
alias ....='cd ../..'

alias c='clear'
alias ll='clear'

alias bash-reload='source ~/.bashrc' 

alias pwdc='pwd | clipboard'
alias pwdce='pwd | clipboard && exit'

alias bashrc-reload='source ~/.bashrc'

alias size='du -sh * | sort -rh'
alias size-all='du -sh .'
