#!/bin/bash

export GITHUB_DIR="$PWD"

printf "\n\n" >> ~/.bashrc
echo "export GITHUB_DIR=\"$PWD\"" >> ~/.bashrc

echo "source $GITHUB_DIR/.configs/colorful_messages" >> ~/.bashrc

echo ". $GITHUB_DIR/.configs/aliases" >> ~/.bashrc
echo ". $GITHUB_DIR/.configs/exports" >> ~/.bashrc

chmod -R +x scripts

source ~/.bashrc

info "Run \`startup\` script to install requirements, update system, etc."