#!/bin/bash
set -e

if [ "$#" -eq 0 ]; then
    echo "No files provided. Please provide at least one file to upload."
    exit 1
fi

for file in "$@"; do
    if [ ! -f "$file" ]; then
        echo "The input '$file' is not valid. Please enter a valid file name."
        continue
    fi

    s3-upload.sh "$file"
    rm "$file"

    echo "Upload of '$file' completed at $(date "+%H:%M:%S")"
done
