#!/bin/bash
set -e

folder_name="$1"
if [ ! -d "$folder_name" ]; then
    echo "PLease enter a valid folder name."
    exit 1
fi

current_datetime=$(date "+%H%M%S-%Y%m%d")
output_filename="$current_datetime.zip"

clear

echo "$output_filename"
zip -r "$output_filename" "$folder_name"/*
rm "$folder_name/*"

clear
echo "Zip completed at $(date "+%H:%M:%S")"
