#!/bin/python3

import argparse
import requests
import os


def send_notif(message: str, token: str, admin_id: int):
    url = f"https://tapi.bale.ai/bot{token}/sendMessage"

    data = {
        "chat_id": admin_id,
        "text": message
    }

    res = requests.post(url, data=data)
    print(res)
    
    
def get_value_or_default(value, default):
    # Check if the value is None or an empty string
    if value is None or value == "":
        return default
    return value


def main():
    # Create the parser
    parser = argparse.ArgumentParser(description='Send a notification to bale bot.')

    # Add the arguments
    parser.add_argument('-m', '--message', type=str, required=True, help='The message to send as a notification')
    parser.add_argument('-t', '--token', type=str, help='The Bale bot token')
    parser.add_argument('-i', '--admin-id', type=int, help='Admin id')

    # Parse the arguments
    args = parser.parse_args()
    message = args.message
    token = get_value_or_default(args.token, os.getenv('BALE_BOT_TOKEN'))
    admin_id = get_value_or_default(args.admin_id, os.getenv('BALE_BOT_ADMIN_ID'))

    # Call the function to send the notification
    send_notif(args.message, token, admin_id)


main()
