#!/bin/python3

import argparse
import requests


def send_notif(message: str, token: str, admin_id: int):
    url = f"https://tapi.bale.ai/bot{token}/sendMessage"

    data = {
        "chat_id": admin_id,
        "text": message
    }

    res = requests.post(url, data=data)
    print(res)


def main():
    # Create the parser
    parser = argparse.ArgumentParser(description='Send a notification to bale bot.')

    # Add the arguments
    parser.add_argument('-m', '--message', type=str, required=True, help='The message to send as a notification')
    parser.add_argument('-t', '--token', type=str, required=True, help='The Bale bot token')
    parser.add_argument('-i', '--admin-id', type=int, required=True, help='Admin id')

    # Parse the arguments
    args = parser.parse_args()

    # Call the function to send the notification
    send_notif(args.message, args.token, args.admin_id)


main()
