#!/bin/bash

install_aria2(){
    python3 -m pip install --upgrade pip
    python3 -m pip install brotli
    sudo apt install -y aria2
    #python3 -m pip install --force-reinstall yt-dlp
}

nano "$GITHUB_DIR/.configs/exports"
source ~/.bashrc # reload exports

update

sudo apt install -y python3-pip
pip install -r "$GITHUB_DIR/.configs/pip-requirements.txt"

sudo pip3 install yt-dlp
sudo apt install -y ffmpeg

sudo apt install -y yt-dlp
sudo apt install -y xclip
install_aria2

s3-install