#!/bin/bash

nano "$GITHUB_DIR/.configs/exports"
source ~/.bashrc # reload exports

update

sudo apt install -y python3-pip
pip install -r "$GITHUB_DIR/.configs/pip-requirements.txt"

install-yt-dlp
sudo apt install -y ffmpeg

sudo apt install -y aria2
sudo apt install -y yt-dlp
sudo apt install -y xclip

s3-install